FROM        node:12

# The base node image sets a very verbose log level.
ENV NPM_CONFIG_LOGLEVEL warn

RUN         echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc

EXPOSE      3000

RUN         mkdir -p /cv-editor/web
WORKDIR     /cv-editor/web

ENTRYPOINT  ["sleep", "2d"]